spring:
  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  web:
    # Static resources reloading during development
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        cachecontrol:
          no-cache: true